=== Valeram12/Javalab/Laba7/src/main/java/dealer.dtd
<!ELEMENT Dealer (Manufacturers*)>
        <!ELEMENT Manufacturers (Brands*)>
        <!ELEMENT Brands (#PCDATA)>
        <!ATTLIST Manufacturers
                id ID #REQUIRED
                name CDATA #REQUIRED
                >
        <!ATTLIST Brands
                id ID #REQUIRED
                manufacturersId IDREF #REQUIRED
                name CDATA #REQUIRED
                releaseYear CDATA #REQUIRED
                >

=== Valeram12/Javalab/Laba7/src/main/java/dealer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Dealer SYSTEM "dealer.dtd">
<Dealer><Brands id="manufacturers2" name="Toyota"><Brands id="id2" manufacturersId="manufacturers2" name="Crown" releaseYear="1957"/><Brands id="id5" manufacturersId="manufacturers2" name="2000Gt" releaseYear="1967"/></Brands><Brands id="manufacturers3" name="Ford Motor Company"><Brands id="id3" manufacturersId="manufacturers3" name="Model T" releaseYear="1910"/><Brands id="id4" manufacturersId="manufacturers3" name="F150" releaseYear="2017"/></Brands><Brands id="manufacturers0" name="Hyundai Motor Group"><Brands id="id0" manufacturersId="manufacturers0" name="Pony" releaseYear="1982"/></Brands><Brands id="manufacturers1" name="Volkswagen Group"><Brands id="id1" manufacturersId="manufacturers1" name="Beetle" releaseYear="1951"/></Brands></Dealer>
